### ISSUE TITLE
[Issue] 

### ISSUE THREAD

**Issue by MichaelYochpaz** [MichaelYochpaz/issue-forms-test#2]
### Confirmations

- [X] I confirm that I checked the issues tab and couldn't find an existing open issue for the same issue I'm having.

### OS Type

Windows

### Python Version

3.10.5

### Package Version

2.3.2

### Run Command

isubrip <url>

### Description

test

### Config

```TOML
[downloads]
format = "srt"
zip = true
merge-playlists = false

[subtitles]
remove-duplicates = true
fix-rtl = false
```

### Output Log

```Shell
C:\Users\Michael> python -m pip show isubrip
Name: isubrip
Version: 2.3.2
Summary: A Python package for scraping and downloading subtitles from iTunes movie pages.
Home-page: https://github.com/MichaelYochpaz/iSubRip
Author: Michael Yochpaz
Author-email:
License: MIT
Location: c:\users\micha\appdata\roaming\python\python310\site-packages
Requires: aiohttp, beautifulsoup4, lxml, m3u8, mergedeep, requests, tomli
Required-by:
```
